version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      MONGO_URI: mongodb://fastapi-db-1:27017/test
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
volumes:
  data: